Document: kaldi
Title: Debian kaldi Manual
Author: <insert document author here>
Abstract: This manual describes what kaldi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kaldi/kaldi.sgml.gz

Format: postscript
Files: /usr/share/doc/kaldi/kaldi.ps.gz

Format: text
Files: /usr/share/doc/kaldi/kaldi.text.gz

Format: HTML
Index: /usr/share/doc/kaldi/html/index.html
Files: /usr/share/doc/kaldi/html/*.html
